spring.application.name=DocumetIngetion

#Setting up directories
source.directory = C:\\Users\\ramkd\\OneDrive\\Pictures\\Source
destiantion.directory = C:\\Users\\ramkd\\OneDrive\\Pictures\\Destination